name: Source code WebCUtils (sessions)
on:
  push:
    branches:
      - sessions

jobs:
  publish_source:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Comprime codigo
        run: zip -r source_code.zip .

      - name: Publica el zip
        uses: actions/upload-artifact@v3
        with:
          name: Source code.zip
          path: source_code.zip
