name: Source code WebCUtils
on:
  push:
    branches:
      - main

jobs:
  publish_source:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Comprimir código
        run: zip -r source_code.zip .

      - name: Publicar archivo ZIP
        uses: actions/upload-artifact@v3
        with:
          name: Source code.zip
          path: source_code.zip
